name = "morning-digest"
main = "index.js"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 4 * * *"]

[[kv_namespaces]]
binding = "ARTICLES_KV"
id = "c6d9c3ed9d3e45d9b9b509c7a22272ae"
preview_id = "cfa6cedc195d4346ab2d0bad04b6e8cc"

[vars]
ENVIRONMENT = "production"